name: Tests

on:
  push:
    paths-ignore:
    - 'Tests/**'
    - 'README.md'

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install google tests manualy
      run: cdelv/googletest-action@master
    - name: run tests
      run: make test
