name: Tests

on:
  push:
    paths-ignore:
    - 'Tests/**'
    - 'README.md'

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install google tests 
      run: sudo apt-get update && sudo apt-get install -y -f libgtest-dev
    - name: run tests
      run: make test
